services:
  - type: web
    name: food-detection-web-demo
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.server:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
